# Generated by Django 5.2.17 on 2026-09-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='size',
            field=models.PositiveBigIntegerField(),
        ),
    ]
